import SwiftUI

extension Image {
    public static let customBackShort: Image = Image("back short").resizable()
    public static let customBack: Image = Image("back").resizable()
    public static let customBox: Image = Image("box").resizable()
    public static let customCall: Image = Image("call").resizable()
    public static let customChart: Image = Image("chart").resizable()
    public static let customClock: Image = Image("clock").resizable()
    public static let customDate: Image = Image("date").resizable()
    public static let customExtra: Image = Image("extra").resizable()
    public static let customFile: Image = Image("file").resizable()
    public static let customFilter: Image = Image("filter").resizable()
    public static let customHome: Image = Image("home").resizable()
    public static let customMarker: Image = Image("map marker").resizable()
    public static let customMessage: Image = Image("message").resizable()
    public static let customMinus: Image = Image("minus").resizable()
    public static let customPlus: Image = Image("plus").resizable()
    public static let customRoute: Image = Image("route").resizable()
    public static let customSearch: Image = Image("search").resizable()
    public static let customUser: Image = Image("user").resizable()
    public static let customEye: Image = Image("eye").resizable()
    public static let customClosedEye: Image = Image("eye closed").resizable()
    public static let customPencil: Image = Image("pencil").resizable()
    public static let customBin: Image = Image("bin").resizable()
    public static let customImage: Image = Image("image").resizable()
    public static let customReload: Image = Image("reload").resizable()

    public static let customErrorAlert: Image = Image("error alert").resizable()
    public static let customSuccessAlert: Image = Image("success alert").resizable()
    public static let customInfoAlert: Image = Image("info alert").resizable()
}
